//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEVICE_MASTER
    {
        public decimal DEVICE_ID { get; set; }
        public Nullable<int> CLIENT_ID { get; set; }
        public string DEVICE_GUID { get; set; }
        public string DEVICE_NAME { get; set; }
        public string MODEL_NAME { get; set; }
        public string FACTORY_NAME { get; set; }
        public string DEVICE_OS { get; set; }
        public Nullable<int> DEVICE_TYPE { get; set; }
        public string OS_VERSION { get; set; }
        public string REGIS_ID { get; set; }
        public Nullable<System.DateTime> REGIS_DATE { get; set; }
    
        public virtual CLIENT_MASTER CLIENT_MASTER { get; set; }
    }
}
