//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HELP_LINK
    {
        public int HELP_LINK_ID { get; set; }
        public Nullable<byte> USER_TYPE_ID { get; set; }
        public Nullable<int> LANGUAGE_ID { get; set; }
        public string HELP_LINK_NAME { get; set; }
        public string HELP_LINK_DESC { get; set; }
        public string HELP_LINK_URL { get; set; }
        public Nullable<short> SEQ_NO { get; set; }
    
        public virtual SYS_USER_TYPE SYS_USER_TYPE { get; set; }
        public virtual SYS_LANGUAGE SYS_LANGUAGE { get; set; }
    }
}
