//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class STGY_SMAPEntities : DbContext
    {
        public STGY_SMAPEntities()
            : base("name=STGY_SMAPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CLIENT_MASTER> CLIENT_MASTER { get; set; }
        public DbSet<DEVICE_MASTER> DEVICE_MASTER { get; set; }
        public DbSet<EMAIL_TEMPLATE> EMAIL_TEMPLATE { get; set; }
        public DbSet<HELP_LINK> HELP_LINK { get; set; }
        public DbSet<SEC_GROUP> SEC_GROUP { get; set; }
        public DbSet<SEC_GROUP_CAPTION> SEC_GROUP_CAPTION { get; set; }
        public DbSet<SEC_LOG_INFO> SEC_LOG_INFO { get; set; }
        public DbSet<SEC_OBJECT> SEC_OBJECT { get; set; }
        public DbSet<SEC_OBJECT_CAPTION> SEC_OBJECT_CAPTION { get; set; }
        public DbSet<SEC_ROLE> SEC_ROLE { get; set; }
        public DbSet<SEC_ROLE_PERMISSION> SEC_ROLE_PERMISSION { get; set; }
        public DbSet<SEC_USER> SEC_USER { get; set; }
        public DbSet<SYS_APP_CAPTION> SYS_APP_CAPTION { get; set; }
        public DbSet<SYS_LANGUAGE> SYS_LANGUAGE { get; set; }
        public DbSet<SYS_USER_TYPE> SYS_USER_TYPE { get; set; }
    }
}
