//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEC_GROUP
    {
        public SEC_GROUP()
        {
            this.SEC_GROUP_CAPTION = new HashSet<SEC_GROUP_CAPTION>();
            this.SEC_OBJECT = new HashSet<SEC_OBJECT>();
        }
    
        public byte SEC_GROUP_ID { get; set; }
        public string URL_PATH { get; set; }
        public string ICON_PATH { get; set; }
        public Nullable<byte> SEQ_NO { get; set; }
    
        public virtual ICollection<SEC_GROUP_CAPTION> SEC_GROUP_CAPTION { get; set; }
        public virtual ICollection<SEC_OBJECT> SEC_OBJECT { get; set; }
    }
}
