//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEC_USER
    {
        public SEC_USER()
        {
            this.CLIENT_MASTER = new HashSet<CLIENT_MASTER>();
            this.CLIENT_MASTER1 = new HashSet<CLIENT_MASTER>();
            this.SEC_LOG_INFO = new HashSet<SEC_LOG_INFO>();
        }
    
        public decimal USER_ID { get; set; }
        public Nullable<byte> USER_TYPE_ID { get; set; }
        public string USER_NAME { get; set; }
        public string PWD_TXT { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string EMAIL_ID { get; set; }
        public string MOBILE_NO { get; set; }
        public Nullable<int> SEC_ROLE_ID { get; set; }
        public Nullable<bool> ACCOUNT_STATUS { get; set; }
        public Nullable<int> LANGUAGE_ID { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
    
        public virtual ICollection<CLIENT_MASTER> CLIENT_MASTER { get; set; }
        public virtual ICollection<CLIENT_MASTER> CLIENT_MASTER1 { get; set; }
        public virtual ICollection<SEC_LOG_INFO> SEC_LOG_INFO { get; set; }
        public virtual SEC_ROLE SEC_ROLE { get; set; }
        public virtual SYS_LANGUAGE SYS_LANGUAGE { get; set; }
        public virtual SYS_USER_TYPE SYS_USER_TYPE { get; set; }
    }
}
