//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEC_OBJECT_CAPTION
    {
        public int SEC_OBJ_ID { get; set; }
        public int LANGUAGE_ID { get; set; }
        public string SEC_OBJ_DESC { get; set; }
    
        public virtual SEC_OBJECT SEC_OBJECT { get; set; }
        public virtual SYS_LANGUAGE SYS_LANGUAGE { get; set; }
    }
}
