//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEC_ROLE_PERMISSION
    {
        public int SEC_ROLE_ID { get; set; }
        public int SEC_OBJ_ID { get; set; }
        public Nullable<bool> VIEW_OPT { get; set; }
        public Nullable<bool> ADD_OPT { get; set; }
        public Nullable<bool> EDIT_OPT { get; set; }
        public Nullable<bool> DEL_OPT { get; set; }
        public Nullable<bool> EXPORT_OPT { get; set; }
        public Nullable<bool> PRINT_OPT { get; set; }
        public Nullable<bool> EMAIL_OPT { get; set; }
    
        public virtual SEC_OBJECT SEC_OBJECT { get; set; }
        public virtual SEC_ROLE SEC_ROLE { get; set; }
    }
}
