//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEC_ROLE
    {
        public SEC_ROLE()
        {
            this.SEC_ROLE_PERMISSION = new HashSet<SEC_ROLE_PERMISSION>();
            this.SEC_USER = new HashSet<SEC_USER>();
        }
    
        public int SEC_ROLE_ID { get; set; }
        public string SEC_ROLE_NAME { get; set; }
        public string SEC_ROLE_DESC { get; set; }
    
        public virtual ICollection<SEC_ROLE_PERMISSION> SEC_ROLE_PERMISSION { get; set; }
        public virtual ICollection<SEC_USER> SEC_USER { get; set; }
    }
}
