//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEC_OBJECT
    {
        public SEC_OBJECT()
        {
            this.SEC_ROLE_PERMISSION = new HashSet<SEC_ROLE_PERMISSION>();
            this.SEC_OBJECT_CAPTION = new HashSet<SEC_OBJECT_CAPTION>();
        }
    
        public int SEC_OBJ_ID { get; set; }
        public Nullable<byte> SEC_GROUP_ID { get; set; }
        public string URL_PATH { get; set; }
        public string ICON_PATH { get; set; }
        public Nullable<byte> SEQ_NO { get; set; }
    
        public virtual SEC_GROUP SEC_GROUP { get; set; }
        public virtual ICollection<SEC_ROLE_PERMISSION> SEC_ROLE_PERMISSION { get; set; }
        public virtual ICollection<SEC_OBJECT_CAPTION> SEC_OBJECT_CAPTION { get; set; }
    }
}
