//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_LANGUAGE
    {
        public SYS_LANGUAGE()
        {
            this.EMAIL_TEMPLATE = new HashSet<EMAIL_TEMPLATE>();
            this.HELP_LINK = new HashSet<HELP_LINK>();
            this.SEC_GROUP_CAPTION = new HashSet<SEC_GROUP_CAPTION>();
            this.SEC_OBJECT_CAPTION = new HashSet<SEC_OBJECT_CAPTION>();
            this.SEC_USER = new HashSet<SEC_USER>();
            this.SYS_APP_CAPTION = new HashSet<SYS_APP_CAPTION>();
        }
    
        public int LANGUAGE_ID { get; set; }
        public string LANGUAGE_NAME { get; set; }
        public string LANGUAGE_CODE { get; set; }
    
        public virtual ICollection<EMAIL_TEMPLATE> EMAIL_TEMPLATE { get; set; }
        public virtual ICollection<HELP_LINK> HELP_LINK { get; set; }
        public virtual ICollection<SEC_GROUP_CAPTION> SEC_GROUP_CAPTION { get; set; }
        public virtual ICollection<SEC_OBJECT_CAPTION> SEC_OBJECT_CAPTION { get; set; }
        public virtual ICollection<SEC_USER> SEC_USER { get; set; }
        public virtual ICollection<SYS_APP_CAPTION> SYS_APP_CAPTION { get; set; }
    }
}
