//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_APP_CAPTION
    {
        public int APP_CAPTION_ID { get; set; }
        public Nullable<int> APP_CAPTION_CODE { get; set; }
        public Nullable<int> LANGUAGE_ID { get; set; }
        public string APP_CAPTION_TEXT { get; set; }
    
        public virtual SYS_LANGUAGE SYS_LANGUAGE { get; set; }
    }
}
