//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_USER_TYPE
    {
        public SYS_USER_TYPE()
        {
            this.HELP_LINK = new HashSet<HELP_LINK>();
            this.SEC_USER = new HashSet<SEC_USER>();
        }
    
        public byte USER_TYPE_ID { get; set; }
        public string USER_TYPE_DESC { get; set; }
    
        public virtual ICollection<HELP_LINK> HELP_LINK { get; set; }
        public virtual ICollection<SEC_USER> SEC_USER { get; set; }
    }
}
