//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Encrypt_master
    {
        public int Enc_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> project_id { get; set; }
        public string source_id { get; set; }
    
        public virtual Project_Master Project_Master { get; set; }
        public virtual sec_user sec_user { get; set; }
    }
}
