//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ESS_DBEntities : DbContext
    {
        public ESS_DBEntities()
            : base("name=ESS_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Encrypt_master> Encrypt_master { get; set; }
        public DbSet<Project_Master> Project_Master { get; set; }
        public DbSet<sec_user> sec_user { get; set; }
        public DbSet<Sec_user_log> Sec_user_log { get; set; }
        public DbSet<SYS_TIME_CONVERSION> SYS_TIME_CONVERSION { get; set; }
    }
}
