//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project_Master
    {
        public Project_Master()
        {
            this.Encrypt_master = new HashSet<Encrypt_master>();
        }
    
        public int Project_Id { get; set; }
        public string Project_Name { get; set; }
        public string Connect_String { get; set; }
        public Nullable<int> User_id { get; set; }
        public Nullable<System.DateTime> Date_created { get; set; }
    
        public virtual ICollection<Encrypt_master> Encrypt_master { get; set; }
        public virtual sec_user sec_user { get; set; }
    }
}
