//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sec_user_log
    {
        public int Log_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<System.DateTime> Date_entry { get; set; }
    
        public virtual sec_user sec_user { get; set; }
    }
}
